import 'dart:io';

import 'package:mason/mason.dart';
import 'package:path/path.dart' as p;

import '../models/architecture.dart';
import '../templates/bloc_app_template.dart';
import '../templates/getx_app_template.dart';
import '../templates/provider_app_template.dart';
import '../templates/riverpod_app_template.dart';

/// Generates a Flutter project with the chosen architecture.
class ProjectGenerator {
  const ProjectGenerator({required Logger logger}) : _logger = logger;

  final Logger _logger;

  /// Generates the project files inside [outputDirectory].
  ///
  /// 1. Runs `flutter create` to scaffold platform directories.
  /// 2. Overlays the architecture template on top.
  ///
  /// Returns the list of generated template files.
  Future<List<GeneratedFile>> generate({
    required String projectName,
    required Architecture architecture,
    required Directory outputDirectory,
    String description = 'A Flutter project generated by relax CLI.',
    String primaryColor = '6750A4',
    String fontFamily = 'Roboto',
  }) async {
    // Step 1: scaffold with flutter create
    await _flutterCreate(
      projectName: projectName,
      description: description,
      outputDirectory: outputDirectory,
    );

    // Step 2: overlay architecture template
    final files = switch (architecture) {
      Architecture.bloc => BlocAppTemplate.files,
      Architecture.provider => ProviderAppTemplate.files,
      Architecture.riverpod => RiverpodAppTemplate.files,
      Architecture.getx => GetxAppTemplate.files,
    };

    final generator = MasonGenerator(
      '${architecture.name}_app',
      'Flutter app with ${architecture.label} architecture.',
      files: files,
      vars: ['project_name', 'description', 'primary_color', 'font_family'],
    );

    final target = DirectoryGeneratorTarget(outputDirectory);

    final generatedFiles = await generator.generate(
      target,
      vars: <String, dynamic>{
        'project_name': projectName,
        'description': description,
        'primary_color': primaryColor,
        'font_family': fontFamily,
      },
      fileConflictResolution: FileConflictResolution.overwrite,
      logger: _logger,
    );

    // Step 3: run env_builder to generate packages/env from .env files
    await _runEnvBuilder(
      projectDir: Directory(p.join(outputDirectory.path, projectName)),
    );

    return generatedFiles;
  }

  /// Runs `flutter create` to generate platform directories.
  ///
  /// If Flutter is not installed, logs a warning and continues
  /// (the project will lack platform dirs but lib/ will still work).
  Future<void> _flutterCreate({
    required String projectName,
    required String description,
    required Directory outputDirectory,
  }) async {
    final progress = _logger.progress('Running flutter create');

    try {
      final result = await Process.run(
        'flutter',
        [
          'create',
          '--project-name',
          projectName,
          '--description',
          description,
          '--org',
          'com.example',
          p.join(outputDirectory.path, projectName),
        ],
        runInShell: true,
      );

      if (result.exitCode == 0) {
        progress.complete('Flutter scaffold created');

        // Remove default main.dart — we use flavor entry points
        final defaultMain = File(
          p.join(outputDirectory.path, projectName, 'lib', 'main.dart'),
        );
        if (defaultMain.existsSync()) defaultMain.deleteSync();

        // Remove default test — we provide our own
        final defaultTest = File(
          p.join(outputDirectory.path, projectName, 'test', 'widget_test.dart'),
        );
        if (defaultTest.existsSync()) defaultTest.deleteSync();

        // Patch Android build.gradle.kts with flavor config
        await _patchAndroidFlavors(
          projectDir: Directory(p.join(outputDirectory.path, projectName)),
          projectName: projectName,
        );
      } else {
        progress.fail('flutter create exited with code ${result.exitCode}');
        _logger.detail('${result.stderr}'.trim());
      }
    } on ProcessException {
      progress.fail('Flutter not found — skipping platform scaffold');
      _logger.warn(
        'Install Flutter to add platform support (android, ios, web, etc.).\n'
        '  Then run: cd $projectName && flutter create .',
      );
    }
  }

  /// Runs `env_builder build` to generate `packages/env/` from `.env.*` files.
  Future<void> _runEnvBuilder({required Directory projectDir}) async {
    final progress = _logger.progress('Running env_builder build');

    try {
      final result = await Process.run(
        'env_builder',
        [
          'build',
          '-e',
          '.env.development,.env.production,.env.staging',
        ],
        workingDirectory: projectDir.path,
        runInShell: true,
      );

      if (result.exitCode == 0) {
        progress.complete('Environment package generated');
      } else {
        progress.fail('env_builder exited with code ${result.exitCode}');
        _logger.detail('${result.stderr}'.trim());
      }
    } on ProcessException {
      progress.fail('env_builder not found — skipping env generation');
      _logger.warn(
        'Install env_builder_cli to generate the env package:\n'
        '  dart pub global activate env_builder_cli\n'
        '  cd ${projectDir.path} && env_builder build '
        '-e .env.development,.env.production,.env.staging',
      );
    }
  }

  /// Patches `android/app/build.gradle.kts` to add productFlavors.
  Future<void> _patchAndroidFlavors({
    required Directory projectDir,
    required String projectName,
  }) async {
    final buildGradle = File(
      p.join(projectDir.path, 'android', 'app', 'build.gradle.kts'),
    );
    if (!buildGradle.existsSync()) return;

    var content = buildGradle.readAsStringSync();

    // Don't patch if already has flavors
    if (content.contains('productFlavors')) return;

    // Convert snake_case to Title Case for display names
    final displayName = projectName
        .split('_')
        .map((w) => w[0].toUpperCase() + w.substring(1))
        .join(' ');

    final flavorBlock = '''

    flavorDimensions += "default"
    productFlavors {
        create("development") {
            dimension = "default"
            applicationIdSuffix = ".dev"
            resValue("string", "app_name", "$displayName Dev")
        }
        create("staging") {
            dimension = "default"
            applicationIdSuffix = ".stg"
            resValue("string", "app_name", "$displayName Stg")
        }
        create("production") {
            dimension = "default"
            resValue("string", "app_name", "$displayName")
        }
    }''';

    // Find the buildTypes closing brace and insert after it
    final buildTypesEnd = content.indexOf(RegExp(r'buildTypes\s*\{'));
    if (buildTypesEnd == -1) return;

    // Find the matching closing brace of buildTypes
    var depth = 0;
    var insertIndex = -1;
    for (var i = content.indexOf('{', buildTypesEnd); i < content.length; i++) {
      if (content[i] == '{') depth++;
      if (content[i] == '}') depth--;
      if (depth == 0) {
        insertIndex = i + 1;
        break;
      }
    }

    if (insertIndex == -1) return;

    content = '${content.substring(0, insertIndex)}'
        '$flavorBlock'
        '${content.substring(insertIndex)}';

    buildGradle.writeAsStringSync(content);
    _logger.detail('Patched Android build.gradle.kts with flavor config');
  }
}
