import 'dart:io';

import 'package:mason/mason.dart';
import 'package:path/path.dart' as p;

import '../models/architecture.dart';
import '../templates/bloc_app_template.dart';
import '../templates/getx_app_template.dart';
import '../templates/provider_app_template.dart';
import '../templates/riverpod_app_template.dart';

/// Generates a Flutter project with the chosen architecture.
class ProjectGenerator {
  const ProjectGenerator({required Logger logger}) : _logger = logger;

  final Logger _logger;

  /// Generates the project files inside [outputDirectory].
  ///
  /// 1. Runs `flutter create` to scaffold platform directories.
  /// 2. Overlays the architecture template on top.
  /// 3. Uses [org] as the platform package prefix.
  ///
  /// Returns the list of generated template files.
  Future<List<GeneratedFile>> generate({
    required String projectName,
    required Architecture architecture,
    required Directory outputDirectory,
    String org = 'com.example',
    String description = 'A Flutter project generated by relax CLI.',
    String primaryColor = '6750A4',
    String fontFamily = 'Roboto',
  }) async {
    final projectDir = Directory(p.join(outputDirectory.path, projectName));

    // Step 1: scaffold with flutter create
    await _flutterCreate(
      projectName: projectName,
      org: org,
      description: description,
      outputDirectory: outputDirectory,
    );

    // Step 2: write .env files + run env_builder BEFORE mason templates.
    // This ensures packages/env/ exists before pubspec.yaml references it,
    // preventing VS Code from failing on `flutter pub get`.
    await _generateEnvPackage(projectDir: projectDir, projectName: projectName);

    // Step 3: overlay architecture template (pubspec.yaml with env: path: packages/env)
    final files = switch (architecture) {
      Architecture.bloc => BlocAppTemplate.files,
      Architecture.provider => ProviderAppTemplate.files,
      Architecture.riverpod => RiverpodAppTemplate.files,
      Architecture.getx => GetxAppTemplate.files,
    };

    final generator = MasonGenerator(
      '${architecture.name}_app',
      'Flutter app with ${architecture.label} architecture.',
      files: files,
      vars: ['project_name', 'description', 'primary_color', 'font_family'],
    );

    final target = DirectoryGeneratorTarget(outputDirectory);

    final generatedFiles = await generator.generate(
      target,
      vars: <String, dynamic>{
        'project_name': projectName,
        'description': description,
        'primary_color': primaryColor,
        'font_family': fontFamily,
      },
      fileConflictResolution: FileConflictResolution.overwrite,
      logger: _logger,
    );

    // Step 4: run flutter pub get + build_runner to generate slang translations
    await _runBuildRunner(projectDir: projectDir);

    return generatedFiles;
  }

  /// Runs `flutter create` to generate platform directories.
  ///
  /// If Flutter is not installed, logs a warning and continues
  /// (the project will lack platform dirs but lib/ will still work).
  Future<void> _flutterCreate({
    required String projectName,
    required String org,
    required String description,
    required Directory outputDirectory,
  }) async {
    final progress = _logger.progress('Running flutter create');

    try {
      final result = await Process.run('flutter', [
        'create',
        '--project-name',
        projectName,
        '--description',
        description,
        '--org',
        org,
        p.join(outputDirectory.path, projectName),
      ], runInShell: true);

      if (result.exitCode == 0) {
        progress.complete('Flutter scaffold created');

        // Remove default main.dart — we use flavor entry points
        final defaultMain = File(
          p.join(outputDirectory.path, projectName, 'lib', 'main.dart'),
        );
        if (defaultMain.existsSync()) defaultMain.deleteSync();

        // Remove default test — we provide our own
        final defaultTest = File(
          p.join(outputDirectory.path, projectName, 'test', 'widget_test.dart'),
        );
        if (defaultTest.existsSync()) defaultTest.deleteSync();

        // Patch Android build.gradle.kts with flavor config
        await _patchAndroidFlavors(
          projectDir: Directory(p.join(outputDirectory.path, projectName)),
          projectName: projectName,
          org: org,
        );

        // Patch iOS Info.plist with supported locales
        _patchIosLocalizations(
          projectDir: Directory(p.join(outputDirectory.path, projectName)),
        );
      } else {
        progress.fail('flutter create exited with code ${result.exitCode}');
        _logger.detail('${result.stderr}'.trim());
      }
    } on ProcessException {
      progress.fail('Flutter not found — skipping platform scaffold');
      _logger.warn(
        'Install Flutter to add platform support (android, ios, web, etc.).\n'
        '  Then run: cd $projectName && flutter create .',
      );
    }
  }

  /// Writes `.env.*` files and runs `env_builder build` to create
  /// `packages/env/` BEFORE the pubspec.yaml references it.
  Future<void> _generateEnvPackage({
    required Directory projectDir,
    required String projectName,
  }) async {
    final displayName = projectName
        .split('_')
        .map((w) => w[0].toUpperCase() + w.substring(1))
        .join(' ');

    // Write .env files directly (no mason — we need them before templates)
    final envFiles = {
      '.env.development':
          'APP_NAME=$displayName Dev\nAPP_SUFFIX=.dev\nBASE_URL=http://localhost:8080\nENCRYPTION_KEY=encry1234567890ABCDEF12GHIJK34LMNOP098QRSTUVWXYZabcdefghe567ijklmnAoOpqrstuRTDvwxyz0987654321\n',
      '.env.staging':
          'APP_NAME=$displayName Stg\nAPP_SUFFIX=.stg\nBASE_URL=https://staging.api.example.com\nENCRYPTION_KEY=encry1234567890ABCDEF12GHIJK34LMNOP098QRSTUVWXYZabcdefghe567ijklmnAoOpqrstuRTDvwxyz0987654321\n',
      '.env.production':
          'APP_NAME=$displayName\nAPP_SUFFIX=\nBASE_URL=https://api.example.com\nENCRYPTION_KEY=encry1234567890ABCDEF12GHIJK34LMNOP098QRSTUVWXYZabcdefghe567ijklmnAoOpqrstuRTDvwxyz0987654321\n',
    };

    for (final entry in envFiles.entries) {
      File(p.join(projectDir.path, entry.key)).writeAsStringSync(entry.value);
    }

    // Also write a minimal pubspec.yaml so env_builder finds a root project
    File(p.join(projectDir.path, 'pubspec.yaml')).writeAsStringSync(
      'name: $projectName\ndescription: temp\nenvironment:\n  sdk: ^3.6.0\n',
    );

    // Run env_builder build
    final progress = _logger.progress('Running env_builder build');

    try {
      final result = await Process.run(
        'env_builder',
        ['build', '-e', '.env.development,.env.production,.env.staging'],
        workingDirectory: projectDir.path,
        runInShell: true,
      );

      if (result.exitCode == 0) {
        progress.complete('Environment package generated');
      } else {
        progress.fail('env_builder exited with code ${result.exitCode}');
        _logger.detail('${result.stderr}'.trim());
      }
    } on ProcessException {
      progress.fail('env_builder not found — skipping env generation');
      _logger.warn(
        'Install env_builder_cli to generate the env package:\n'
        '  dart pub global activate env_builder_cli\n'
        '  cd ${p.basename(projectDir.path)} && env_builder build '
        '-e .env.development,.env.production,.env.staging',
      );
    }
  }

  /// Runs `flutter pub get` then `build_runner build` to generate slang
  /// translations and any other generated code.
  Future<void> _runBuildRunner({required Directory projectDir}) async {
    // pub get first so build_runner can resolve packages
    final pubGetProgress = _logger.progress('Running flutter pub get');
    try {
      final pubGet = await Process.run(
        'flutter',
        ['pub', 'get'],
        workingDirectory: projectDir.path,
        runInShell: true,
      );
      if (pubGet.exitCode == 0) {
        pubGetProgress.complete('Dependencies resolved');
      } else {
        pubGetProgress.fail(
          'flutter pub get exited with code ${pubGet.exitCode}',
        );
        _logger.detail('${pubGet.stderr}'.trim());
        return;
      }
    } on ProcessException {
      pubGetProgress.fail('Flutter not found — skipping pub get');
      return;
    }

    // Generate slang translations
    final slangProgress = _logger.progress('Running slang (i18n)');
    try {
      final slangResult = await Process.run(
        'dart',
        ['run', 'slang'],
        workingDirectory: projectDir.path,
        runInShell: true,
      );
      if (slangResult.exitCode == 0) {
        slangProgress.complete('Translations generated');
      } else {
        slangProgress.fail('slang exited with code ${slangResult.exitCode}');
        _logger.detail('${slangResult.stderr}'.trim());
      }
    } on ProcessException {
      slangProgress.fail('slang not found — skipping translation generation');
      _logger.warn(
        'Run manually:\n'
        '  cd ${p.basename(projectDir.path)} && dart run slang',
      );
    }

    // Generate other code (RelaxORM, etc.)
    final progress = _logger.progress('Running build_runner');
    try {
      final result = await Process.run(
        'dart',
        ['run', 'build_runner', 'build', '--delete-conflicting-outputs'],
        workingDirectory: projectDir.path,
        runInShell: true,
      );
      if (result.exitCode == 0) {
        progress.complete('Code generation complete');
      } else {
        progress.fail('build_runner exited with code ${result.exitCode}');
        _logger.detail('${result.stderr}'.trim());
      }
    } on ProcessException {
      progress.fail('build_runner not found — skipping code generation');
      _logger.warn(
        'Run manually:\n'
        '  cd ${p.basename(projectDir.path)} && dart run build_runner build '
        '--delete-conflicting-outputs',
      );
    }
  }

  /// Patches iOS Info.plist to declare supported localizations (fr, en).
  void _patchIosLocalizations({required Directory projectDir}) {
    final infoPlist = File(
      p.join(projectDir.path, 'ios', 'Runner', 'Info.plist'),
    );
    if (!infoPlist.existsSync()) return;

    var content = infoPlist.readAsStringSync();

    // Only add if not already present
    if (content.contains('CFBundleLocalizations')) return;

    // Insert before the closing </dict>
    const localizationBlock = '''
\t<key>CFBundleLocalizations</key>
\t<array>
\t\t<string>fr</string>
\t\t<string>en</string>
\t</array>''';

    content = content.replaceFirst(
      '</dict>\n</plist>',
      '$localizationBlock\n</dict>\n</plist>',
    );
    infoPlist.writeAsStringSync(content);

    _logger.detail('Configured iOS localizations (fr, en)');
  }

  /// Configures Android: build.gradle.kts, AndroidManifest.xml, flavor res dirs.
  Future<void> _patchAndroidFlavors({
    required Directory projectDir,
    required String projectName,
    required String org,
  }) async {
    final androidAppDir = p.join(projectDir.path, 'android', 'app');
    final buildGradle = File(p.join(androidAppDir, 'build.gradle.kts'));
    if (!buildGradle.existsSync()) return;

    final displayName = projectName
        .split('_')
        .map((w) => w[0].toUpperCase() + w.substring(1))
        .join(' ');

    // ── 1. Rewrite build.gradle.kts ─────────────────────────────
    buildGradle.writeAsStringSync(
      _buildGradleContent(
        namespace: '$org.$projectName',
        applicationId: '$org.$projectName',
        displayName: displayName,
      ),
    );

    // ── 2. Patch AndroidManifest.xml ────────────────────────────
    final manifest = File(
      p.join(androidAppDir, 'src', 'main', 'AndroidManifest.xml'),
    );
    if (manifest.existsSync()) {
      var xml = manifest.readAsStringSync();
      // Replace android:label="..." with android:label="${appName}"
      xml = xml.replaceAll(
        RegExp(r'android:label="[^"]*"'),
        r'android:label="${appName}"',
      );
      manifest.writeAsStringSync(xml);
    }

    // ── 3. Create flavor res directories ────────────────────────
    for (final flavor in ['development', 'staging']) {
      final resDir = Directory(
        p.join(androidAppDir, 'src', flavor, 'res', 'values'),
      );
      resDir.createSync(recursive: true);

      // Each flavor can override strings, icons, etc.
      File(p.join(resDir.path, 'strings.xml')).writeAsStringSync(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<resources>\n'
        '    <!-- Flavor-specific overrides go here -->\n'
        '</resources>\n',
      );
    }

    _logger.detail('Configured Android flavors, manifest, and res dirs');
  }

  /// Returns the complete `build.gradle.kts` content.
  static String _buildGradleContent({
    required String namespace,
    required String applicationId,
    required String displayName,
  }) =>
      '''
import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.reader(Charsets.UTF_8).use { reader ->
        localProperties.load(reader)
    }
}

val flutterVersionCode = localProperties.getProperty("flutter.versionCode") ?: "1"
val flutterVersionName = localProperties.getProperty("flutter.versionName") ?: "1.0"

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.inputStream().use { stream ->
        keystoreProperties.load(stream)
    }
}

android {
    namespace = "$namespace"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties.getProperty("keyAlias")
            keyPassword = keystoreProperties.getProperty("keyPassword")

            val storeFilePath = keystoreProperties.getProperty("storeFile")
            if (storeFilePath != null) {
                storeFile = file(storeFilePath)
            }

            storePassword = keystoreProperties.getProperty("storePassword")
        }
    }

    defaultConfig {
        applicationId = "$applicationId"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutterVersionCode.toInt()
        versionName = flutterVersionName
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }

        release {
            signingConfig = signingConfigs.getByName("release")
        }
    }

    flavorDimensions += "default"
    productFlavors {
        create("development") {
            dimension = "default"
            applicationIdSuffix = ".dev"
            manifestPlaceholders["appName"] = "$displayName [Dev]"
        }
        create("staging") {
            dimension = "default"
            applicationIdSuffix = ".stg"
            manifestPlaceholders["appName"] = "$displayName [Stg]"
        }
        create("production") {
            dimension = "default"
            applicationIdSuffix = ""
            manifestPlaceholders["appName"] = "$displayName"
        }
    }
}

flutter {
    source = "../.."
}
''';
}
