import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';

import '../../generators/generators.dart';
import '../../models/architecture.dart';
import '../../utils/prompt.dart';

/// Command to create a new Flutter project with a chosen architecture.
class CreateCommand extends Command<int> {
  CreateCommand({required Logger logger}) : _logger = logger {
    argParser
      ..addOption(
        'architecture',
        abbr: 'a',
        help: 'The architecture to use for the project.',
        allowed: Architecture.values.map((a) => a.name),
        allowedHelp: {
          for (final arch in Architecture.values) arch.name: arch.label,
        },
      )
      ..addFlag('org',abbr: 'o',help: '--org com.example')
      ..addOption(
        'description',
        abbr: 'd',
        help: 'Project description for pubspec.yaml.',
        defaultsTo: 'A Flutter project generated by relax CLI.',
      )
      ..addOption(
        'primary-color',
        help: 'Primary seed color as hex (e.g. 6750A4, 1565C0).',
        defaultsTo: '6750A4',
      )
      ..addOption(
        'font',
        help: 'Font family for the app.',
        allowed: ['Roboto', 'Inter', 'Poppins', 'Lato', 'Montserrat'],
        defaultsTo: 'Roboto',
      );
  }

  final Logger _logger;

  @override
  String get name => 'create';

  @override
  String get description =>
      'Create a new Flutter project with a clean architecture.';

  @override
  String get invocation => 'relax create <project_name>';

  @override
  Future<int> run() async {
    final projectName = _getProjectName();
    if (projectName == null) return ExitCode.usage.code;

    if (!_isValidProjectName(projectName)) {
      _logger.err('Invalid project name: "$projectName"');
      _logger.info(
        'Project name must be a valid Dart package name '
        '(lowercase letters, digits, underscores; must start with a letter).',
      );
      return ExitCode.usage.code;
    }

    final outputDir = Directory(projectName);
    if (outputDir.existsSync()) {
      _logger.err('Directory "$projectName" already exists.');
      return ExitCode.usage.code;
    }

    final architecture = _resolveArchitecture();

    _logger.info('');
    _logger.info(lightCyan.wrap(_banner));
    _logger.info('');
    _logger.info(
      'Creating project ${lightCyan.wrap(projectName)} '
      'with ${lightCyan.wrap(architecture.label)} architecture...',
    );
    _logger.info('');

    final description = argResults?['description'] as String;
    final primaryColor = argResults?['primary-color'] as String;
    final font = argResults?['font'] as String;

    final generator = ProjectGenerator(logger: _logger);

    try {
      final generatedFiles = await generator.generate(
        projectName: projectName,
        architecture: architecture,
        outputDirectory: Directory.current,
        description: description,
        primaryColor: primaryColor,
        fontFamily: font,
      );

      _logger.info('');
      _logger.success(
        'Created project "$projectName" with ${architecture.name} '
        '(${generatedFiles.length} files).',
      );
      _logger.info('');
      _logger.info('Next steps:');
      _logger.info('  ${lightCyan.wrap('cd $projectName')}');
      _logger.info('  ${lightCyan.wrap('flutter pub get')}');
      _logger.info('');
      _logger.info('Run a flavor:');
      _logger.info(
        '  ${lightCyan.wrap('flutter run --flavor development -t lib/main_development.dart')}',
      );
      _logger.info(
        '  ${lightCyan.wrap('flutter run --flavor staging -t lib/main_staging.dart')}',
      );
      _logger.info(
        '  ${lightCyan.wrap('flutter run --flavor production -t lib/main_production.dart')}',
      );
      _logger.info('');
      _logger.info('Regenerate translations after editing .i18n.json files:');
      _logger.info(
        '  ${lightCyan.wrap('dart run build_runner build --delete-conflicting-outputs')}',
      );
      _logger.info('');

      return ExitCode.success.code;
    } on UnimplementedError catch (e) {
      _logger.err(e.message ?? 'Architecture not yet supported.');
      return ExitCode.unavailable.code;
    } on FileSystemException catch (e) {
      _logger.err('File system error: ${e.message}');
      if (e.osError != null) {
        _logger.detail('OS error: ${e.osError}');
      }
      return ExitCode.ioError.code;
    } on Exception catch (e) {
      _logger.err('Unexpected error during project generation.');
      _logger.detail('$e');
      return ExitCode.software.code;
    }
  }

  /// Extracts the project name from positional arguments.
  String? _getProjectName() {
    final args = argResults!.rest;
    if (args.isEmpty) {
      _logger.err('No project name specified.');
      _logger.info('Usage: $invocation');
      return null;
    }
    return args.first;
  }

  /// Resolves architecture from flag or interactive prompt.
  Architecture _resolveArchitecture() {
    final archArg = argResults?['architecture'] as String?;
    if (archArg != null) {
      return Architecture.values.byName(archArg);
    }
    return _promptArchitecture();
  }

  /// Interactive prompt for architecture selection.
  Architecture _promptArchitecture() {
    return chooseOneOf<Architecture>(
      _logger,
      message: 'Which architecture would you like to use?',
      choices: Architecture.values.toList(),
      display: (a) => a.label,
      defaultValue: Architecture.bloc,
    );
  }

  /// Validates that [name] is a valid Dart package name.
  bool _isValidProjectName(String name) {
    return RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(name);
  }

  static const _banner = ' _ __ ___| | __ ___  __\n'
      "| '__/ _ \\ |/ _` \\ \\/ /\n"
      '| | |  __/ | (_| |>  < \n'
      r'|_|  \___|_|\__,_/_/\_\';
}
