name: relax_cli
description: >-
  CLI to scaffold Flutter projects with clean architecture,
  state management (Bloc, Provider, Riverpod, GetX), and RelaxORM integration.
version: 0.1.2
repository: https://github.com/KalybosPro/relax_cli
issue_tracker: https://github.com/KalybosPro/relax_cli/issues

topics:
  - cli
  - flutter
  - code-generation
  - clean-architecture
  - orm

platforms:
  windows:
  macos:
  linux:
  android:
  ios:

environment:
  sdk: ^3.11.0

executables:
  relax:

dependencies:
  args: ^2.7.0
  mason: ^0.1.2
  mason_logger: ^0.3.5
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
