/// A very good package generated by Env Builder CLI for environment variables
library;

export 'src/config/app_flavor.dart';
export 'src/enums.dart';
export 'src/env.dev.dart';
export 'src/env.prod.dart';
export 'src/env.stg.dart';
