/// {@template env}
/// A Very Good Package generated by Env Builder CLI.
/// {@endtemplate}
enum Env {

    /// The value for App Name.
  appName('APP_NAME'),

  /// The value for App Suffix.
  appSuffix('APP_SUFFIX'),

  /// The value for Base Url.
  baseUrl('BASE_URL'),

  /// The value for Encryption Key.
  encryptionKey('ENCRYPTION_KEY');

  /// {@macro env}
  const Env(this.name);

  /// The value of the enum class
  final String name;
}

/// Env value signature that can be used to get an environment value, base
/// on provided [Env].
typedef EnvValue = String Function(Env env);
